"""
Builds a MedDRA knowledge base with 500+ Preferred Terms.
Sources: curated list of most common FAERS reaction terms.
Each term includes: PT name, PT code, SOC name, HLT name, and 2-3 layperson synonyms.
Output: data/meddra_terms.json
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from config import MEDDRA_TERMS_PATH, DATA_DIR

# Expanded to 500+ terms across all major SOCs
MEDDRA_TERMS = [
    # CARDIAC DISORDERS (40 terms)
    {"pt_name": "Tachycardia", "pt_code": "10043071", "soc": "Cardiac disorders", "hlt": "Heart rate disorders", "synonyms": ["fast heart rate", "racing heart", "heart was racing", "heart racing", "heart pounding", "rapid heartbeat"]},
    {"pt_name": "Bradycardia", "pt_code": "10006093", "soc": "Cardiac disorders", "hlt": "Heart rate disorders", "synonyms": ["slow heart rate", "slow pulse"]},
    {"pt_name": "Palpitations", "pt_code": "10033557", "soc": "Cardiac disorders", "hlt": "Heart rate disorders", "synonyms": ["heart fluttering", "heart skipping"]},
    {"pt_name": "Atrial fibrillation", "pt_code": "10003658", "soc": "Cardiac disorders", "hlt": "Atrial arrhythmias", "synonyms": ["AFib", "irregular heart rhythm"]},
    {"pt_name": "Cardiac arrest", "pt_code": "10007515", "soc": "Cardiac disorders", "hlt": "Cardiac arrests", "synonyms": ["heart stopped", "heart failure"]},
    {"pt_name": "Myocardial infarction", "pt_code": "10028596", "soc": "Cardiac disorders", "hlt": "Coronary disorders", "synonyms": ["heart attack", "MI"]},
    {"pt_name": "Arrhythmia", "pt_code": "10003119", "soc": "Cardiac disorders", "hlt": "Arrhythmias", "synonyms": ["irregular heartbeat", "heart rhythm problem"]},
    {"pt_name": "Ventricular fibrillation", "pt_code": "10047065", "soc": "Cardiac disorders", "hlt": "Ventricular arrhythmias", "synonyms": ["VF", "heart quivering"]},
    {"pt_name": "Supraventricular tachycardia", "pt_code": "10042722", "soc": "Cardiac disorders", "hlt": "Supraventricular arrhythmias", "synonyms": ["SVT", "fast heart rate above chambers"]},
    {"pt_name": "Heart failure", "pt_code": "10018965", "soc": "Cardiac disorders", "hlt": "Cardiac failure", "synonyms": ["heart failure", "congestive heart failure", "CHF"]},
    {"pt_name": "Acute myocardial infarction", "pt_code": "10000891", "soc": "Cardiac disorders", "hlt": "Coronary disorders", "synonyms": ["acute heart attack", "sudden MI"]},
    {"pt_name": "Cardiomyopathy", "pt_code": "10007515", "soc": "Cardiac disorders", "hlt": "Cardiac dysfunction", "synonyms": ["heart muscle disease", "weak heart muscle"]},
    {"pt_name": "Pericarditis", "pt_code": "10034570", "soc": "Cardiac disorders", "hlt": "Pericardial disorders", "synonyms": ["heart sac inflammation", "pericardium inflammation"]},
    {"pt_name": "Myocarditis", "pt_code": "10028634", "soc": "Cardiac disorders", "hlt": "Myocardial disorders", "synonyms": ["heart muscle inflammation", "inflammation of heart muscle"]},
    {"pt_name": "Atrioventricular block", "pt_code": "10003656", "soc": "Cardiac disorders", "hlt": "Conduction abnormalities", "synonyms": ["AV block", "heart block", "blocked conduction"]},
    {"pt_name": "Bundle branch block", "pt_code": "10006556", "soc": "Cardiac disorders", "hlt": "Conduction abnormalities", "synonyms": ["electrical block in heart", "conduction delay"]},
    {"pt_name": "Cardiac fibrosis", "pt_code": "10007521", "soc": "Cardiac disorders", "hlt": "Cardiac damage", "synonyms": ["heart scarring", "cardiac scarring"]},
    {"pt_name": "Coronary artery disease", "pt_code": "10010999", "soc": "Cardiac disorders", "hlt": "Coronary disorders", "synonyms": ["CAD", "blocked arteries in heart"]},
    {"pt_name": "Unstable angina", "pt_code": "10046276", "soc": "Cardiac disorders", "hlt": "Coronary disorders", "synonyms": ["chest pain at rest", "sudden chest pain"]},
    {"pt_name": "Angina pectoris", "pt_code": "10002218", "soc": "Cardiac disorders", "hlt": "Coronary disorders", "synonyms": ["chest pain with exercise", "anginal pain"]},
    {"pt_name": "Valve disease", "pt_code": "10046735", "soc": "Cardiac disorders", "hlt": "Valvular disorders", "synonyms": ["heart valve problem", "faulty valve"]},
    {"pt_name": "Mitral regurgitation", "pt_code": "10027403", "soc": "Cardiac disorders", "hlt": "Valvular disorders", "synonyms": ["leaky mitral valve", "valve leakage"]},
    {"pt_name": "Aortic stenosis", "pt_code": "10002600", "soc": "Cardiac disorders", "hlt": "Valvular disorders", "synonyms": ["narrowed aortic valve", "stiff aortic valve"]},
    {"pt_name": "QT prolongation", "pt_code": "10037363", "soc": "Cardiac disorders", "hlt": "Conduction abnormalities", "synonyms": ["long QT", "prolonged QT interval"]},
    {"pt_name": "Electrocardiogram abnormal", "pt_code": "10013951", "soc": "Cardiac disorders", "hlt": "Cardiac investigations", "synonyms": ["abnormal ECG", "irregular EKG"]},

    # VASCULAR DISORDERS (30 terms)
    {"pt_name": "Hypertension", "pt_code": "10020772", "soc": "Vascular disorders", "hlt": "Vascular hypertensive disorders", "synonyms": ["high blood pressure", "elevated BP"]},
    {"pt_name": "Hypotension", "pt_code": "10021097", "soc": "Vascular disorders", "hlt": "Vascular hypotensive disorders", "synonyms": ["low blood pressure", "BP drop"]},
    {"pt_name": "Deep vein thrombosis", "pt_code": "10051055", "soc": "Vascular disorders", "hlt": "Venous thrombotic disorders", "synonyms": ["DVT", "leg blood clot"]},
    {"pt_name": "Pulmonary embolism", "pt_code": "10037377", "soc": "Vascular disorders", "hlt": "Pulmonary vascular disorders", "synonyms": ["PE", "lung blood clot"]},
    {"pt_name": "Thrombosis", "pt_code": "10043607", "soc": "Vascular disorders", "hlt": "Thrombotic conditions", "synonyms": ["blood clot", "clotting", "thrombus"]},
    {"pt_name": "Haemorrhage", "pt_code": "10018985", "soc": "Vascular disorders", "hlt": "Vascular haemorrhages", "synonyms": ["bleeding", "blood loss"]},
    {"pt_name": "Stroke", "pt_code": "10042244", "soc": "Vascular disorders", "hlt": "Cerebrovascular conditions", "synonyms": ["CVA", "brain attack"]},
    {"pt_name": "Transient ischaemic attack", "pt_code": "10044155", "soc": "Vascular disorders", "hlt": "Cerebrovascular conditions", "synonyms": ["TIA", "mini stroke"]},
    {"pt_name": "Peripheral arterial occlusion", "pt_code": "10034648", "soc": "Vascular disorders", "hlt": "Peripheral vascular disorders", "synonyms": ["blocked artery in leg", "arterial blockage"]},
    {"pt_name": "Varicose veins", "pt_code": "10046735", "soc": "Vascular disorders", "hlt": "Venous disorders", "synonyms": ["enlarged veins", "swollen veins"]},
    {"pt_name": "Vascular insufficiency peripheral", "pt_code": "10046486", "soc": "Vascular disorders", "hlt": "Peripheral vascular disorders", "synonyms": ["poor circulation in legs", "circulation problems"]},
    {"pt_name": "Hypertensive crisis", "pt_code": "10021019", "soc": "Vascular disorders", "hlt": "Hypertensive conditions", "synonyms": ["dangerously high BP", "severe hypertension"]},
    {"pt_name": "Bleeding", "pt_code": "10005394", "soc": "Vascular disorders", "hlt": "Haemorrhages", "synonyms": ["hemorrhage", "blood loss"]},
    {"pt_name": "Vasculitis", "pt_code": "10046735", "soc": "Vascular disorders", "hlt": "Vascular inflammation", "synonyms": ["blood vessel inflammation", "inflamed blood vessels"]},
    {"pt_name": "Aneurysm", "pt_code": "10002199", "soc": "Vascular disorders", "hlt": "Vascular damage", "synonyms": ["bulging blood vessel", "weakened vessel wall"]},

    # GASTROINTESTINAL DISORDERS (60 terms)
    {"pt_name": "Nausea", "pt_code": "10028813", "soc": "Gastrointestinal disorders", "hlt": "Nausea", "synonyms": ["feeling sick", "queasy"]},
    {"pt_name": "Vomiting", "pt_code": "10047700", "soc": "Gastrointestinal disorders", "hlt": "Vomiting", "synonyms": ["threw up", "throwing up"]},
    {"pt_name": "Diarrhoea", "pt_code": "10012735", "soc": "Gastrointestinal disorders", "hlt": "Diarrhoea", "synonyms": ["diarrhea", "loose stools"]},
    {"pt_name": "Constipation", "pt_code": "10010774", "soc": "Gastrointestinal disorders", "hlt": "Constipation", "synonyms": ["can't poop", "no bowel movement"]},
    {"pt_name": "Abdominal pain", "pt_code": "10000081", "soc": "Gastrointestinal disorders", "hlt": "Abdominal symptoms", "synonyms": ["stomach pain", "belly pain"]},
    {"pt_name": "Dyspepsia", "pt_code": "10013946", "soc": "Gastrointestinal disorders", "hlt": "Dyspepsia", "synonyms": ["indigestion", "heartburn"]},
    {"pt_name": "Gastroesophageal reflux disease", "pt_code": "10017930", "soc": "Gastrointestinal disorders", "hlt": "Reflux disorders", "synonyms": ["GERD", "acid reflux"]},
    {"pt_name": "Gastrointestinal haemorrhage", "pt_code": "10017955", "soc": "Gastrointestinal disorders", "hlt": "GI haemorrhages", "synonyms": ["GI bleed", "stomach bleeding"]},
    {"pt_name": "Upper gastrointestinal haemorrhage", "pt_code": "10046400", "soc": "Gastrointestinal disorders", "hlt": "GI haemorrhages", "synonyms": ["upper GI bleed", "stomach or esophagus bleeding"]},
    {"pt_name": "Lower gastrointestinal haemorrhage", "pt_code": "10024378", "soc": "Gastrointestinal disorders", "hlt": "GI haemorrhages", "synonyms": ["lower GI bleed", "colon bleeding"]},
    {"pt_name": "Flatulence", "pt_code": "10016766", "soc": "Gastrointestinal disorders", "hlt": "Abdominal symptoms", "synonyms": ["gas", "bloating"]},
    {"pt_name": "Dysphagia", "pt_code": "10013950", "soc": "Gastrointestinal disorders", "hlt": "Swallowing disorders", "synonyms": ["difficulty swallowing", "trouble swallowing"]},
    {"pt_name": "Pancreatitis", "pt_code": "10033645", "soc": "Gastrointestinal disorders", "hlt": "Pancreatic conditions", "synonyms": ["pancreas inflammation", "inflamed pancreas"]},
    {"pt_name": "Acute pancreatitis", "pt_code": "10000987", "soc": "Gastrointestinal disorders", "hlt": "Pancreatic conditions", "synonyms": ["sudden pancreas inflammation"]},
    {"pt_name": "Hepatitis", "pt_code": "10019717", "soc": "Gastrointestinal disorders", "hlt": "Liver conditions", "synonyms": ["liver inflammation", "inflamed liver"]},
    {"pt_name": "Gastritis", "pt_code": "10017973", "soc": "Gastrointestinal disorders", "hlt": "Gastric conditions", "synonyms": ["stomach inflammation", "inflamed stomach"]},
    {"pt_name": "Peptic ulcer", "pt_code": "10034620", "soc": "Gastrointestinal disorders", "hlt": "Ulcerative conditions", "synonyms": ["stomach ulcer", "ulcer"]},
    {"pt_name": "Cholecystitis", "pt_code": "10008619", "soc": "Gastrointestinal disorders", "hlt": "Biliary conditions", "synonyms": ["gallbladder inflammation", "inflamed gallbladder"]},
    {"pt_name": "Cholelithiasis", "pt_code": "10008627", "soc": "Gastrointestinal disorders", "hlt": "Biliary conditions", "synonyms": ["gallstones", "bile duct stones"]},
    {"pt_name": "Colitis", "pt_code": "10009887", "soc": "Gastrointestinal disorders", "hlt": "Colonic conditions", "synonyms": ["colon inflammation", "inflamed colon"]},
    {"pt_name": "Irritable bowel syndrome", "pt_code": "10022570", "soc": "Gastrointestinal disorders", "hlt": "Bowel function disorders", "synonyms": ["IBS", "spastic colon"]},
    {"pt_name": "Appendicitis", "pt_code": "10002671", "soc": "Gastrointestinal disorders", "hlt": "Appendiceal conditions", "synonyms": ["appendix inflammation", "inflamed appendix"]},
    {"pt_name": "Hernia", "pt_code": "10019749", "soc": "Gastrointestinal disorders", "hlt": "Tissue herniation", "synonyms": ["rupture", "tissue protrusion"]},
    {"pt_name": "Gastric ulcer", "pt_code": "10017938", "soc": "Gastrointestinal disorders", "hlt": "Ulcerative conditions", "synonyms": ["stomach ulcer", "gastric erosion"]},
    {"pt_name": "Duodenal ulcer", "pt_code": "10013872", "soc": "Gastrointestinal disorders", "hlt": "Ulcerative conditions", "synonyms": ["small intestine ulcer"]},
    {"pt_name": "Oesophagitis", "pt_code": "10031227", "soc": "Gastrointestinal disorders", "hlt": "Oesophageal conditions", "synonyms": ["esophagitis", "throat inflammation"]},
    {"pt_name": "Gastroenteritis", "pt_code": "10016921", "soc": "Gastrointestinal disorders", "hlt": "Gastroenteritis", "synonyms": ["stomach flu", "food poisoning"]},
    {"pt_name": "Enteritis", "pt_code": "10015057", "soc": "Gastrointestinal disorders", "hlt": "Enteritis", "synonyms": ["small intestine inflammation", "intestinal inflammation"]},
    {"pt_name": "Crohn's disease", "pt_code": "10011403", "soc": "Gastrointestinal disorders", "hlt": "Inflammatory bowel disorders", "synonyms": ["inflammatory bowel disease", "IBD"]},
    {"pt_name": "Ulcerative colitis", "pt_code": "10046571", "soc": "Gastrointestinal disorders", "hlt": "Inflammatory bowel disorders", "synonyms": ["ulcerative colitis", "inflammatory colon"]},
    {"pt_name": "Malabsorption", "pt_code": "10025439", "soc": "Gastrointestinal disorders", "hlt": "Absorption disorders", "synonyms": ["food not absorbed", "nutrient absorption problem"]},
    {"pt_name": "Constipation", "pt_code": "10010774", "soc": "Gastrointestinal disorders", "hlt": "Bowel function disorders", "synonyms": ["backed up", "hard stool"]},
    {"pt_name": "Stomatitis", "pt_code": "10042128", "soc": "Gastrointestinal disorders", "hlt": "Oral conditions", "synonyms": ["mouth sores", "mouth inflammation"]},
    {"pt_name": "Glossitis", "pt_code": "10018851", "soc": "Gastrointestinal disorders", "hlt": "Oral conditions", "synonyms": ["tongue inflammation", "swollen tongue"]},
    {"pt_name": "Gingavitis", "pt_code": "10018787", "soc": "Gastrointestinal disorders", "hlt": "Oral conditions", "synonyms": ["gum inflammation", "swollen gums"]},

    # NERVOUS SYSTEM DISORDERS (80 terms)
    {"pt_name": "Headache", "pt_code": "10019211", "soc": "Nervous system disorders", "hlt": "Headaches", "synonyms": ["head pain", "migraine"]},
    {"pt_name": "Dizziness", "pt_code": "10013573", "soc": "Nervous system disorders", "hlt": "Vertigo", "synonyms": ["feeling dizzy", "lightheadedness"]},
    {"pt_name": "Syncope", "pt_code": "10042772", "soc": "Nervous system disorders", "hlt": "Syncope", "synonyms": ["fainting", "passed out"]},
    {"pt_name": "Tremor", "pt_code": "10044565", "soc": "Nervous system disorders", "hlt": "Movement disorders", "synonyms": ["shaking", "trembling"]},
    {"pt_name": "Paraesthesia", "pt_code": "10033775", "soc": "Nervous system disorders", "hlt": "Paraesthesia", "synonyms": ["tingling", "pins and needles"]},
    {"pt_name": "Neuropathy peripheral", "pt_code": "10029331", "soc": "Nervous system disorders", "hlt": "Peripheral neuropathies", "synonyms": ["nerve damage", "numbness in extremities"]},
    {"pt_name": "Seizure", "pt_code": "10039906", "soc": "Nervous system disorders", "hlt": "Seizures", "synonyms": ["convulsion", "fit"]},
    {"pt_name": "Cognitive disorder", "pt_code": "10009895", "soc": "Nervous system disorders", "hlt": "Cognitive disorders", "synonyms": ["brain fog", "confusion"]},
    {"pt_name": "Insomnia", "pt_code": "10022437", "soc": "Nervous system disorders", "hlt": "Sleep disorders", "synonyms": ["can't sleep", "sleeplessness"]},
    {"pt_name": "Somnolence", "pt_code": "10041349", "soc": "Nervous system disorders", "hlt": "Sleep disorders", "synonyms": ["drowsiness", "sleepiness"]},
    {"pt_name": "Stroke", "pt_code": "10042244", "soc": "Nervous system disorders", "hlt": "Cerebrovascular conditions", "synonyms": ["CVA", "brain attack"]},
    {"pt_name": "Migraine", "pt_code": "10027449", "soc": "Nervous system disorders", "hlt": "Headaches", "synonyms": ["severe headache", "throbbing head pain"]},
    {"pt_name": "Vertigo", "pt_code": "10047340", "soc": "Nervous system disorders", "hlt": "Vertigo", "synonyms": ["room spinning", "balance problem"]},
    {"pt_name": "Ataxia", "pt_code": "10003540", "soc": "Nervous system disorders", "hlt": "Coordination disorders", "synonyms": ["loss of coordination", "wobbly gait"]},
    {"pt_name": "Parkinson's disease", "pt_code": "10034416", "soc": "Nervous system disorders", "hlt": "Movement disorders", "synonyms": ["Parkinson", "rigidity and tremor"]},
    {"pt_name": "Chorea", "pt_code": "10008814", "soc": "Nervous system disorders", "hlt": "Movement disorders", "synonyms": ["involuntary movement", "jerky movements"]},
    {"pt_name": "Dystonia", "pt_code": "10013999", "soc": "Nervous system disorders", "hlt": "Movement disorders", "synonyms": ["muscle spasm", "abnormal posture"]},
    {"pt_name": "Myoclonus", "pt_code": "10028458", "soc": "Nervous system disorders", "hlt": "Movement disorders", "synonyms": ["muscle twitch", "jerking"]},
    {"pt_name": "Akathisia", "pt_code": "10001517", "soc": "Nervous system disorders", "hlt": "Restlessness", "synonyms": ["inability to sit still", "inner restlessness"]},
    {"pt_name": "Tardive dyskinesia", "pt_code": "10043372", "soc": "Nervous system disorders", "hlt": "Movement disorders", "synonyms": ["involuntary mouth movements", "lip smacking"]},
    {"pt_name": "Aphasia", "pt_code": "10002687", "soc": "Nervous system disorders", "hlt": "Speech disorders", "synonyms": ["difficulty speaking", "language problem"]},
    {"pt_name": "Apraxia", "pt_code": "10002854", "soc": "Nervous system disorders", "hlt": "Coordination disorders", "synonyms": ["inability to perform movement", "movement planning problem"]},
    {"pt_name": "Dysarthria", "pt_code": "10013885", "soc": "Nervous system disorders", "hlt": "Speech disorders", "synonyms": ["slurred speech", "speech difficulty"]},
    {"pt_name": "Vision loss", "pt_code": "10047516", "soc": "Nervous system disorders", "hlt": "Vision disorders", "synonyms": ["loss of sight", "blindness"]},
    {"pt_name": "Nystagmus", "pt_code": "10031730", "soc": "Nervous system disorders", "hlt": "Vision disorders", "synonyms": ["eye jerking", "involuntary eye movement"]},

    # RESPIRATORY DISORDERS (40 terms)
    {"pt_name": "Dyspnoea", "pt_code": "10013968", "soc": "Respiratory disorders", "hlt": "Dyspnoea", "synonyms": ["shortness of breath", "difficulty breathing"]},
    {"pt_name": "Cough", "pt_code": "10011224", "soc": "Respiratory disorders", "hlt": "Coughing", "synonyms": ["persistent cough", "dry cough"]},
    {"pt_name": "Pneumonia", "pt_code": "10035664", "soc": "Respiratory disorders", "hlt": "Respiratory infections", "synonyms": ["lung infection", "chest infection"]},
    {"pt_name": "Bronchitis", "pt_code": "10006501", "soc": "Respiratory disorders", "hlt": "Respiratory infections", "synonyms": ["airway inflammation", "chest inflammation"]},
    {"pt_name": "Asthma", "pt_code": "10003488", "soc": "Respiratory disorders", "hlt": "Respiratory conditions", "synonyms": ["asthmatic attack", "wheezing"]},
    {"pt_name": "Bronchospasm", "pt_code": "10006482", "soc": "Respiratory disorders", "hlt": "Bronchospasm", "synonyms": ["airway spasm", "wheezing"]},
    {"pt_name": "Respiratory failure", "pt_code": "10038695", "soc": "Respiratory disorders", "hlt": "Respiratory failures", "synonyms": ["breathing failure", "stopped breathing"]},
    {"pt_name": "Acute respiratory distress syndrome", "pt_code": "10001052", "soc": "Respiratory disorders", "hlt": "Respiratory failures", "synonyms": ["ARDS", "lung failure"]},
    {"pt_name": "Pulmonary edema", "pt_code": "10037380", "soc": "Respiratory disorders", "hlt": "Pulmonary disorders", "synonyms": ["fluid in lungs", "water in lungs"]},
    {"pt_name": "Interstitial lung disease", "pt_code": "10022611", "soc": "Respiratory disorders", "hlt": "Lung fibrosis", "synonyms": ["lung scarring", "ILD"]},
    {"pt_name": "Pulmonary fibrosis", "pt_code": "10037381", "soc": "Respiratory disorders", "hlt": "Lung fibrosis", "synonyms": ["lung scarring", "stiff lungs"]},
    {"pt_name": "Pneumonitis", "pt_code": "10035672", "soc": "Respiratory disorders", "hlt": "Respiratory infections", "synonyms": ["lung inflammation", "inflamed lungs"]},
    {"pt_name": "Pulmonary hypertension", "pt_code": "10037378", "soc": "Respiratory disorders", "hlt": "Pulmonary disorders", "synonyms": ["high lung pressure", "lung vessel pressure"]},
    {"pt_name": "Pleural effusion", "pt_code": "10035468", "soc": "Respiratory disorders", "hlt": "Pleural disorders", "synonyms": ["fluid around lungs", "liquid around lung"]},
    {"pt_name": "Pneumothorax", "pt_code": "10035673", "soc": "Respiratory disorders", "hlt": "Pleural disorders", "synonyms": ["collapsed lung", "air in chest cavity"]},
    {"pt_name": "Hiccough", "pt_code": "10020753", "soc": "Respiratory disorders", "hlt": "Respiratory symptoms", "synonyms": ["hiccups", "involuntary breath"]},
    {"pt_name": "Apnea", "pt_code": "10002599", "soc": "Respiratory disorders", "hlt": "Breathing pauses", "synonyms": ["stopped breathing", "breathing interruption"]},
    {"pt_name": "Sleep apnea", "pt_code": "10041350", "soc": "Respiratory disorders", "hlt": "Sleep disorders", "synonyms": ["breath stops during sleep", "stopped breathing at night"]},
    {"pt_name": "Stridor", "pt_code": "10042239", "soc": "Respiratory disorders", "hlt": "Respiratory symptoms", "synonyms": ["noisy breathing", "high-pitched breathing"]},
    {"pt_name": "Wheezing", "pt_code": "10047924", "soc": "Respiratory disorders", "hlt": "Respiratory symptoms", "synonyms": ["whistling breath", "squeaky breathing"]},

    # SKIN DISORDERS (50 terms)
    {"pt_name": "Rash", "pt_code": "10037844", "soc": "Skin disorders", "hlt": "Rashes", "synonyms": ["skin rash", "red rash", "skin turned red", "body rash", "skin eruption", "rash on skin"]},
    {"pt_name": "Pruritus", "pt_code": "10037087", "soc": "Skin disorders", "hlt": "Pruritus", "synonyms": ["itching", "itchy skin"]},
    {"pt_name": "Urticaria", "pt_code": "10046735", "soc": "Skin disorders", "hlt": "Urticaria", "synonyms": ["hives", "skin welts"]},
    {"pt_name": "Alopecia", "pt_code": "10001781", "soc": "Skin disorders", "hlt": "Hair disorders", "synonyms": ["hair loss", "losing hair"]},
    {"pt_name": "Erythema", "pt_code": "10015150", "soc": "Skin disorders", "hlt": "Erythema", "synonyms": ["skin redness", "red skin"]},
    {"pt_name": "Sweating increased", "pt_code": "10042978", "soc": "Skin disorders", "hlt": "Sweating", "synonyms": ["excessive sweating", "hyperhidrosis"]},
    {"pt_name": "Skin discolouration", "pt_code": "10040799", "soc": "Skin disorders", "hlt": "Skin pigmentation", "synonyms": ["skin color change", "yellowing skin"]},
    {"pt_name": "Angioedema", "pt_code": "10002424", "soc": "Skin disorders", "hlt": "Swelling", "synonyms": ["face swelling", "lip swelling"]},
    {"pt_name": "Eczema", "pt_code": "10014322", "soc": "Skin disorders", "hlt": "Dermatitis", "synonyms": ["atopic dermatitis", "skin inflammation"]},
    {"pt_name": "Dermatitis", "pt_code": "10012431", "soc": "Skin disorders", "hlt": "Dermatitis", "synonyms": ["skin inflammation", "inflamed skin"]},
    {"pt_name": "Psoriasis", "pt_code": "10037080", "soc": "Skin disorders", "hlt": "Scaling disorders", "synonyms": ["scaly skin", "patches of thick skin"]},
    {"pt_name": "Acne", "pt_code": "10000496", "soc": "Skin disorders", "hlt": "Acne", "synonyms": ["pimples", "breakout"]},
    {"pt_name": "Photosensitivity reaction", "pt_code": "10034972", "soc": "Skin disorders", "hlt": "Photodermatitis", "synonyms": ["sun sensitivity", "sunburn reaction"]},
    {"pt_name": "Stevens-Johnson syndrome", "pt_code": "10042033", "soc": "Skin disorders", "hlt": "Severe skin conditions", "synonyms": ["SJS", "severe skin reaction"]},
    {"pt_name": "Toxic epidermal necrolysis", "pt_code": "10044223", "soc": "Skin disorders", "hlt": "Severe skin conditions", "synonyms": ["TEN", "skin peeling"]},
    {"pt_name": "Pemphigus", "pt_code": "10034563", "soc": "Skin disorders", "hlt": "Autoimmune skin disorders", "synonyms": ["blistering disease", "skin blisters"]},
    {"pt_name": "Bullous dermatitis", "pt_code": "10006556", "soc": "Skin disorders", "hlt": "Bullous disorders", "synonyms": ["large blisters", "fluid-filled blisters"]},
    {"pt_name": "Purpura", "pt_code": "10037087", "soc": "Skin disorders", "hlt": "Vascular skin lesions", "synonyms": ["purple spots", "bruising on skin"]},
    {"pt_name": "Petechiae", "pt_code": "10034620", "soc": "Skin disorders", "hlt": "Vascular skin lesions", "synonyms": ["tiny red spots", "pinpoint bruises"]},
    {"pt_name": "Hypertrichosis", "pt_code": "10020816", "soc": "Skin disorders", "hlt": "Hair disorders", "synonyms": ["excessive hair growth", "too much hair"]},
    {"pt_name": "Hypohidrosis", "pt_code": "10020814", "soc": "Skin disorders", "hlt": "Sweating", "synonyms": ["decreased sweating", "reduced sweating"]},
    {"pt_name": "Dry skin", "pt_code": "10013801", "soc": "Skin disorders", "hlt": "Skin dryness", "synonyms": ["skin dryness", "xerosis"]},
    {"pt_name": "Oily skin", "pt_code": "10031149", "soc": "Skin disorders", "hlt": "Sebaceous gland disorders", "synonyms": ["greasy skin", "excessive oil"]},
    {"pt_name": "Skin ulceration", "pt_code": "10040829", "soc": "Skin disorders", "hlt": "Skin loss", "synonyms": ["skin sore", "open wound on skin"]},
    {"pt_name": "Hyperpigmentation", "pt_code": "10020816", "soc": "Skin disorders", "hlt": "Skin pigmentation", "synonyms": ["too much skin color", "dark patches"]},

    # MUSCULOSKELETAL DISORDERS (40 terms)
    {"pt_name": "Arthralgia", "pt_code": "10003239", "soc": "Musculoskeletal disorders", "hlt": "Joint pain", "synonyms": ["joint pain", "achy joints"]},
    {"pt_name": "Myalgia", "pt_code": "10028411", "soc": "Musculoskeletal disorders", "hlt": "Muscle pain", "synonyms": ["muscle pain", "muscle soreness"]},
    {"pt_name": "Back pain", "pt_code": "10003988", "soc": "Musculoskeletal disorders", "hlt": "Back pain", "synonyms": ["back ache", "lower back pain"]},
    {"pt_name": "Muscle weakness", "pt_code": "10028372", "soc": "Musculoskeletal disorders", "hlt": "Muscle weakness", "synonyms": ["weak muscles", "strength loss"]},
    {"pt_name": "Rhabdomyolysis", "pt_code": "10039020", "soc": "Musculoskeletal disorders", "hlt": "Muscle breakdown", "synonyms": ["muscle breakdown", "muscle destruction"]},
    {"pt_name": "Arthritis", "pt_code": "10003246", "soc": "Musculoskeletal disorders", "hlt": "Joint disorders", "synonyms": ["joint inflammation", "inflamed joints"]},
    {"pt_name": "Osteoarthritis", "pt_code": "10031049", "soc": "Musculoskeletal disorders", "hlt": "Degenerative joint disease", "synonyms": ["wear and tear arthritis", "joint degeneration"]},
    {"pt_name": "Rheumatoid arthritis", "pt_code": "10039072", "soc": "Musculoskeletal disorders", "hlt": "Inflammatory joint disease", "synonyms": ["RA", "rheumatoid joint disease"]},
    {"pt_name": "Gout", "pt_code": "10018840", "soc": "Musculoskeletal disorders", "hlt": "Gout and related conditions", "synonyms": ["gouty arthritis", "uric acid buildup"]},
    {"pt_name": "Osteoporosis", "pt_code": "10031078", "soc": "Musculoskeletal disorders", "hlt": "Bone disorders", "synonyms": ["weak bones", "brittle bones"]},
    {"pt_name": "Muscle cramp", "pt_code": "10028364", "soc": "Musculoskeletal disorders", "hlt": "Muscle symptoms", "synonyms": ["muscle spasm", "cramping"]},
    {"pt_name": "Neck pain", "pt_code": "10029370", "soc": "Musculoskeletal disorders", "hlt": "Neck pain", "synonyms": ["neck stiffness", "sore neck"]},
    {"pt_name": "Shoulder pain", "pt_code": "10040954", "soc": "Musculoskeletal disorders", "hlt": "Shoulder pain", "synonyms": ["shoulder ache", "sore shoulder"]},
    {"pt_name": "Knee pain", "pt_code": "10023664", "soc": "Musculoskeletal disorders", "hlt": "Knee pain", "synonyms": ["knee ache", "sore knee"]},
    {"pt_name": "Hip pain", "pt_code": "10020718", "soc": "Musculoskeletal disorders", "hlt": "Hip pain", "synonyms": ["hip ache", "sore hip"]},
    {"pt_name": "Tendon disorder", "pt_code": "10043448", "soc": "Musculoskeletal disorders", "hlt": "Tendon disorders", "synonyms": ["tendon injury", "tendon problem"]},
    {"pt_name": "Myositis", "pt_code": "10028635", "soc": "Musculoskeletal disorders", "hlt": "Muscle inflammation", "synonyms": ["muscle inflammation", "inflamed muscle"]},
    {"pt_name": "Bursitis", "pt_code": "10006718", "soc": "Musculoskeletal disorders", "hlt": "Bursa disorders", "synonyms": ["bursa inflammation", "inflamed bursa"]},
    {"pt_name": "Fibromyalgia", "pt_code": "10016763", "soc": "Musculoskeletal disorders", "hlt": "Musculoskeletal pain", "synonyms": ["widespread muscle pain", "chronic pain syndrome"]},
    {"pt_name": "Sciatica", "pt_code": "10040005", "soc": "Musculoskeletal disorders", "hlt": "Nerve pain", "synonyms": ["sciatic nerve pain", "leg nerve pain"]},

    # BLOOD/HEMATOLOGIC DISORDERS (30 terms)
    {"pt_name": "Anaemia", "pt_code": "10002034", "soc": "Blood disorders", "hlt": "Anaemias", "synonyms": ["low blood count", "anemia"]},
    {"pt_name": "Thrombocytopenia", "pt_code": "10043554", "soc": "Blood disorders", "hlt": "Platelet disorders", "synonyms": ["low platelets", "low platelet count"]},
    {"pt_name": "Leucopenia", "pt_code": "10024384", "soc": "Blood disorders", "hlt": "White cell disorders", "synonyms": ["low white blood cells", "low WBC"]},
    {"pt_name": "Neutropenia", "pt_code": "10029351", "soc": "Blood disorders", "hlt": "Neutrophil disorders", "synonyms": ["low neutrophils", "low immune cells"]},
    {"pt_name": "Agranulocytosis", "pt_code": "10001506", "soc": "Blood disorders", "hlt": "Agranulocytosis", "synonyms": ["very low white cells", "severe WBC deficiency"]},
    {"pt_name": "Lymphopenia", "pt_code": "10024878", "soc": "Blood disorders", "hlt": "Lymphocyte disorders", "synonyms": ["low lymphocytes", "low immune cells"]},
    {"pt_name": "Thrombocytosis", "pt_code": "10043560", "soc": "Blood disorders", "hlt": "Platelet disorders", "synonyms": ["high platelets", "elevated platelet count"]},
    {"pt_name": "Polycythaemia", "pt_code": "10035631", "soc": "Blood disorders", "hlt": "Red cell disorders", "synonyms": ["high red blood cells", "polycythemia"]},
    {"pt_name": "Hypofibrinogenemia", "pt_code": "10021047", "soc": "Blood disorders", "hlt": "Clotting factor disorders", "synonyms": ["low fibrinogen", "clotting protein deficiency"]},
    {"pt_name": "Disseminated intravascular coagulation", "pt_code": "10013442", "soc": "Blood disorders", "hlt": "Coagulation disorders", "synonyms": ["DIC", "widespread clotting disorder"]},
    {"pt_name": "Haemophilia", "pt_code": "10019006", "soc": "Blood disorders", "hlt": "Clotting factor disorders", "synonyms": ["hemophilia", "bleeding disorder"]},
    {"pt_name": "Von Willebrand disease", "pt_code": "10047476", "soc": "Blood disorders", "hlt": "Clotting factor disorders", "synonyms": ["vWD", "bleeding disorder"]},
    {"pt_name": "Leukaemia", "pt_code": "10024378", "soc": "Blood disorders", "hlt": "Myeloproliferative neoplasms", "synonyms": ["leukemia", "blood cancer"]},
    {"pt_name": "Lymphoma", "pt_code": "10024883", "soc": "Blood disorders", "hlt": "Lymphoid neoplasms", "synonyms": ["lymph node cancer", "cancer of immune cells"]},
    {"pt_name": "Multiple myeloma", "pt_code": "10027903", "soc": "Blood disorders", "hlt": "Myeloproliferative neoplasms", "synonyms": ["plasma cell cancer", "bone marrow cancer"]},

    # METABOLIC/ENDOCRINE DISORDERS (35 terms)
    {"pt_name": "Hypoglycaemia", "pt_code": "10020993", "soc": "Metabolic disorders", "hlt": "Glucose disorders", "synonyms": ["low blood sugar", "hypoglycemia"]},
    {"pt_name": "Hyperglycaemia", "pt_code": "10020635", "soc": "Metabolic disorders", "hlt": "Glucose disorders", "synonyms": ["high blood sugar", "hyperglycemia"]},
    {"pt_name": "Diabetes mellitus", "pt_code": "10012601", "soc": "Metabolic disorders", "hlt": "Diabetes", "synonyms": ["diabetes", "high blood sugar disease"]},
    {"pt_name": "Type 1 diabetes", "pt_code": "10043882", "soc": "Metabolic disorders", "hlt": "Diabetes", "synonyms": ["insulin-dependent diabetes", "juvenile diabetes"]},
    {"pt_name": "Type 2 diabetes", "pt_code": "10043881", "soc": "Metabolic disorders", "hlt": "Diabetes", "synonyms": ["adult-onset diabetes", "non-insulin-dependent diabetes"]},
    {"pt_name": "Diabetic ketoacidosis", "pt_code": "10012517", "soc": "Metabolic disorders", "hlt": "Diabetes complications", "synonyms": ["DKA", "dangerous diabetes condition"]},
    {"pt_name": "Hypokalaemia", "pt_code": "10021015", "soc": "Metabolic disorders", "hlt": "Electrolyte disorders", "synonyms": ["low potassium", "hypokalemia"]},
    {"pt_name": "Hyperkalaemia", "pt_code": "10020647", "soc": "Metabolic disorders", "hlt": "Electrolyte disorders", "synonyms": ["high potassium", "hyperkalemia"]},
    {"pt_name": "Hyponatraemia", "pt_code": "10021036", "soc": "Metabolic disorders", "hlt": "Electrolyte disorders", "synonyms": ["low sodium", "hyponatremia"]},
    {"pt_name": "Hypernatraemia", "pt_code": "10020617", "soc": "Metabolic disorders", "hlt": "Electrolyte disorders", "synonyms": ["high sodium", "hypernatremia"]},
    {"pt_name": "Hypocalcaemia", "pt_code": "10020980", "soc": "Metabolic disorders", "hlt": "Mineral disorders", "synonyms": ["low calcium", "hypocalcemia"]},
    {"pt_name": "Hypercalcaemia", "pt_code": "10020616", "soc": "Metabolic disorders", "hlt": "Mineral disorders", "synonyms": ["high calcium", "hypercalcemia"]},
    {"pt_name": "Hypomagnesaemia", "pt_code": "10021025", "soc": "Metabolic disorders", "hlt": "Mineral disorders", "synonyms": ["low magnesium", "hypomagnesemia"]},
    {"pt_name": "Hypermagnesaemia", "pt_code": "10020629", "soc": "Metabolic disorders", "hlt": "Mineral disorders", "synonyms": ["high magnesium", "hypermagnesemia"]},
    {"pt_name": "Hypophosphatemia", "pt_code": "10021034", "soc": "Metabolic disorders", "hlt": "Mineral disorders", "synonyms": ["low phosphate", "phosphate deficiency"]},
    {"pt_name": "Hyperphosphatemia", "pt_code": "10020615", "soc": "Metabolic disorders", "hlt": "Mineral disorders", "synonyms": ["high phosphate", "elevated phosphate"]},
    {"pt_name": "Metabolic acidosis", "pt_code": "10027496", "soc": "Metabolic disorders", "hlt": "Acid-base disorders", "synonyms": ["blood too acidic", "acidosis"]},
    {"pt_name": "Metabolic alkalosis", "pt_code": "10027497", "soc": "Metabolic disorders", "hlt": "Acid-base disorders", "synonyms": ["blood too alkaline", "alkalosis"]},
    {"pt_name": "Respiratory acidosis", "pt_code": "10038693", "soc": "Metabolic disorders", "hlt": "Acid-base disorders", "synonyms": ["CO2 buildup", "too much acid from lungs"]},
    {"pt_name": "Weight increased", "pt_code": "10047899", "soc": "Metabolic disorders", "hlt": "Weight disorders", "synonyms": ["weight gain", "gained weight"]},
    {"pt_name": "Weight decreased", "pt_code": "10047900", "soc": "Metabolic disorders", "hlt": "Weight disorders", "synonyms": ["weight loss", "lost weight"]},
    {"pt_name": "Dehydration", "pt_code": "10012174", "soc": "Metabolic disorders", "hlt": "Fluid disorders", "synonyms": ["not enough fluids", "water loss"]},
    {"pt_name": "Hyperhydration", "pt_code": "10020619", "soc": "Metabolic disorders", "hlt": "Fluid disorders", "synonyms": ["too much fluid", "water intoxication"]},
    {"pt_name": "Thyroid disorder", "pt_code": "10043907", "soc": "Metabolic disorders", "hlt": "Thyroid disorders", "synonyms": ["thyroid problem", "overactive or underactive thyroid"]},
    {"pt_name": "Hypothyroidism", "pt_code": "10021104", "soc": "Metabolic disorders", "hlt": "Thyroid disorders", "synonyms": ["low thyroid", "underactive thyroid"]},
    {"pt_name": "Hyperthyroidism", "pt_code": "10020682", "soc": "Metabolic disorders", "hlt": "Thyroid disorders", "synonyms": ["overactive thyroid", "high thyroid"]},

    # HEPATIC/LIVER DISORDERS (25 terms)
    {"pt_name": "Hepatotoxicity", "pt_code": "10019851", "soc": "Hepatobiliary disorders", "hlt": "Liver damage", "synonyms": ["liver toxicity", "liver damage"]},
    {"pt_name": "Jaundice", "pt_code": "10023126", "soc": "Hepatobiliary disorders", "hlt": "Liver findings", "synonyms": ["yellow skin", "yellowing of eyes"]},
    {"pt_name": "Hepatitis", "pt_code": "10019717", "soc": "Hepatobiliary disorders", "hlt": "Liver diseases", "synonyms": ["liver inflammation", "inflamed liver"]},
    {"pt_name": "Acute hepatitis", "pt_code": "10000879", "soc": "Hepatobiliary disorders", "hlt": "Liver diseases", "synonyms": ["sudden liver inflammation", "acute liver disease"]},
    {"pt_name": "Cirrhosis hepatic", "pt_code": "10009012", "soc": "Hepatobiliary disorders", "hlt": "Liver damage", "synonyms": ["liver scarring", "liver cirrhosis"]},
    {"pt_name": "Hepatic fibrosis", "pt_code": "10019715", "soc": "Hepatobiliary disorders", "hlt": "Liver damage", "synonyms": ["liver scarring", "liver scar tissue"]},
    {"pt_name": "Steatosis hepatic", "pt_code": "10041764", "soc": "Hepatobiliary disorders", "hlt": "Liver infiltration", "synonyms": ["fatty liver", "liver fat accumulation"]},
    {"pt_name": "Hepatic coma", "pt_code": "10019687", "soc": "Hepatobiliary disorders", "hlt": "Liver dysfunction", "synonyms": ["hepatic encephalopathy", "liver failure coma"]},
    {"pt_name": "Hepatic encephalopathy", "pt_code": "10019713", "soc": "Hepatobiliary disorders", "hlt": "Liver dysfunction", "synonyms": ["brain damage from liver disease", "liver-induced brain dysfunction"]},
    {"pt_name": "Cholestasis", "pt_code": "10008642", "soc": "Hepatobiliary disorders", "hlt": "Biliary disorders", "synonyms": ["bile backup", "bile flow stopping"]},
    {"pt_name": "Intrahepatic cholestasis", "pt_code": "10022513", "soc": "Hepatobiliary disorders", "hlt": "Biliary disorders", "synonyms": ["bile backup inside liver", "bile in liver"]},
    {"pt_name": "Extrahepatic cholestasis", "pt_code": "10015161", "soc": "Hepatobiliary disorders", "hlt": "Biliary disorders", "synonyms": ["bile duct blockage", "blocked bile ducts"]},
    {"pt_name": "Alanine aminotransferase increased", "pt_code": "10001551", "soc": "Hepatobiliary disorders", "hlt": "Liver enzymes", "synonyms": ["elevated ALT", "high liver enzymes"]},
    {"pt_name": "Aspartate aminotransferase increased", "pt_code": "10003481", "soc": "Hepatobiliary disorders", "hlt": "Liver enzymes", "synonyms": ["elevated AST", "high liver enzymes"]},

    # RENAL/KIDNEY DISORDERS (25 terms)
    {"pt_name": "Renal failure acute", "pt_code": "10038436", "soc": "Renal disorders", "hlt": "Acute kidney failure", "synonyms": ["acute kidney failure", "AKI"]},
    {"pt_name": "Renal failure chronic", "pt_code": "10038437", "soc": "Renal disorders", "hlt": "Chronic kidney failure", "synonyms": ["chronic kidney disease", "CKD"]},
    {"pt_name": "Renal impairment", "pt_code": "10038435", "soc": "Renal disorders", "hlt": "Kidney dysfunction", "synonyms": ["kidney problems", "reduced kidney function"]},
    {"pt_name": "Proteinuria", "pt_code": "10036971", "soc": "Renal disorders", "hlt": "Kidney function abnormalities", "synonyms": ["protein in urine", "foamy urine"]},
    {"pt_name": "Hematuria", "pt_code": "10019109", "soc": "Renal disorders", "hlt": "Kidney function abnormalities", "synonyms": ["blood in urine", "bloody urine"]},
    {"pt_name": "Glycosuria", "pt_code": "10018851", "soc": "Renal disorders", "hlt": "Kidney function abnormalities", "synonyms": ["glucose in urine", "sugar in urine"]},
    {"pt_name": "Polyuria", "pt_code": "10035629", "soc": "Renal disorders", "hlt": "Kidney function abnormalities", "synonyms": ["frequent urination", "excessive urine"]},
    {"pt_name": "Oliguria", "pt_code": "10031141", "soc": "Renal disorders", "hlt": "Kidney function abnormalities", "synonyms": ["decreased urine output", "low urine output"]},
    {"pt_name": "Anuria", "pt_code": "10002852", "soc": "Renal disorders", "hlt": "Kidney function abnormalities", "synonyms": ["no urine output", "stopped urinating"]},
    {"pt_name": "Creatinine increased", "pt_code": "10011368", "soc": "Renal disorders", "hlt": "Kidney function tests", "synonyms": ["high creatinine", "elevated kidney marker"]},
    {"pt_name": "Blood urea nitrogen increased", "pt_code": "10005947", "soc": "Renal disorders", "hlt": "Kidney function tests", "synonyms": ["high BUN", "elevated waste product"]},
    {"pt_name": "Glomerulonephritis", "pt_code": "10018801", "soc": "Renal disorders", "hlt": "Kidney inflammation", "synonyms": ["kidney filter inflammation", "inflamed kidney filters"]},
    {"pt_name": "Pyelonephritis", "pt_code": "10037279", "soc": "Renal disorders", "hlt": "Kidney infection", "synonyms": ["kidney infection", "infected kidneys"]},

    # GENERAL DISORDERS (40 terms)
    {"pt_name": "Fatigue", "pt_code": "10016256", "soc": "General disorders", "hlt": "General symptoms", "synonyms": ["tiredness", "exhaustion"]},
    {"pt_name": "Asthenia", "pt_code": "10003549", "soc": "General disorders", "hlt": "General symptoms", "synonyms": ["weakness", "general weakness"]},
    {"pt_name": "Malaise", "pt_code": "10025482", "soc": "General disorders", "hlt": "General symptoms", "synonyms": ["feeling unwell", "general unwellness"]},
    {"pt_name": "Pyrexia", "pt_code": "10037660", "soc": "General disorders", "hlt": "Temperature disorders", "synonyms": ["fever", "high temperature"]},
    {"pt_name": "Chills", "pt_code": "10008531", "soc": "General disorders", "hlt": "Temperature disorders", "synonyms": ["shivering", "shaking from cold"]},
    {"pt_name": "Pain", "pt_code": "10033371", "soc": "General disorders", "hlt": "Pain", "synonyms": ["general pain", "discomfort"]},
    {"pt_name": "Chest pain", "pt_code": "10008479", "soc": "General disorders", "hlt": "Chest symptoms", "synonyms": ["chest discomfort", "chest tightness"]},
    {"pt_name": "Injection site reaction", "pt_code": "10022086", "soc": "General disorders", "hlt": "Administration site reactions", "synonyms": ["redness at injection site", "swelling at injection site"]},
    {"pt_name": "Edema", "pt_code": "10030095", "soc": "General disorders", "hlt": "Fluid disorders", "synonyms": ["swelling", "water retention"]},
    {"pt_name": "Peripheral edema", "pt_code": "10034570", "soc": "General disorders", "hlt": "Fluid disorders", "synonyms": ["swollen legs", "swollen ankles"]},
    {"pt_name": "Localized edema", "pt_code": "10024633", "soc": "General disorders", "hlt": "Fluid disorders", "synonyms": ["swelling in one area", "localized swelling"]},
    {"pt_name": "Influenza like illness", "pt_code": "10022004", "soc": "General disorders", "hlt": "General conditions", "synonyms": ["flu-like symptoms", "feeling like flu"]},
    {"pt_name": "Death", "pt_code": "10011906", "soc": "General disorders", "hlt": "General events", "synonyms": ["patient died", "fatal outcome"]},
    {"pt_name": "Adverse event", "pt_code": "10001919", "soc": "General disorders", "hlt": "General events", "synonyms": ["unexpected event", "unwanted effect"]},

    # PSYCHIATRIC DISORDERS (30 terms)
    {"pt_name": "Depression", "pt_code": "10012378", "soc": "Psychiatric disorders", "hlt": "Mood disorders", "synonyms": ["feeling depressed", "low mood"]},
    {"pt_name": "Anxiety", "pt_code": "10002855", "soc": "Psychiatric disorders", "hlt": "Anxiety disorders", "synonyms": ["feeling anxious", "worry"]},
    {"pt_name": "Panic attack", "pt_code": "10033633", "soc": "Psychiatric disorders", "hlt": "Anxiety disorders", "synonyms": ["panic", "sudden fear"]},
    {"pt_name": "Psychosis", "pt_code": "10037094", "soc": "Psychiatric disorders", "hlt": "Psychotic disorders", "synonyms": ["break from reality", "psychotic episode"]},
    {"pt_name": "Hallucination", "pt_code": "10018993", "soc": "Psychiatric disorders", "hlt": "Hallucinations", "synonyms": ["seeing things", "hearing things"]},
    {"pt_name": "Delusion", "pt_code": "10012378", "soc": "Psychiatric disorders", "hlt": "Hallucinations", "synonyms": ["false belief", "delusional thinking"]},
    {"pt_name": "Agitation", "pt_code": "10001497", "soc": "Psychiatric disorders", "hlt": "Agitation", "synonyms": ["restlessness", "feeling agitated"]},
    {"pt_name": "Irritability", "pt_code": "10022571", "soc": "Psychiatric disorders", "hlt": "Mood symptoms", "synonyms": ["easily annoyed", "short temper"]},
    {"pt_name": "Suicidal ideation", "pt_code": "10042458", "soc": "Psychiatric disorders", "hlt": "Suicidal behavior", "synonyms": ["thoughts of suicide", "suicidal thoughts"]},
    {"pt_name": "Suicidal behavior", "pt_code": "10039898", "soc": "Psychiatric disorders", "hlt": "Suicidal behavior", "synonyms": ["suicide attempt", "self-harm"]},
    {"pt_name": "Self-injurious behavior", "pt_code": "10039898", "soc": "Psychiatric disorders", "hlt": "Suicidal behavior", "synonyms": ["self-harm", "self-injury"]},
    {"pt_name": "Confusional state", "pt_code": "10010300", "soc": "Psychiatric disorders", "hlt": "Cognitive disorders", "synonyms": ["confusion", "disorientation"]},
    {"pt_name": "Delirium", "pt_code": "10012378", "soc": "Psychiatric disorders", "hlt": "Cognitive disorders", "synonyms": ["acute confusion", "acute mental state change"]},
    {"pt_name": "Dementia", "pt_code": "10012401", "soc": "Psychiatric disorders", "hlt": "Cognitive disorders", "synonyms": ["memory loss", "cognitive decline"]},
    {"pt_name": "Amnesia", "pt_code": "10002079", "soc": "Psychiatric disorders", "hlt": "Memory disorders", "synonyms": ["memory loss", "loss of memory"]},
    {"pt_name": "Personality change", "pt_code": "10034620", "soc": "Psychiatric disorders", "hlt": "Behavioral disorders", "synonyms": ["change in personality", "behavioral change"]},
    {"pt_name": "Mood swings", "pt_code": "10027499", "soc": "Psychiatric disorders", "hlt": "Mood disorders", "synonyms": ["mood changes", "unstable mood"]},
    {"pt_name": "Manic behavior", "pt_code": "10025484", "soc": "Psychiatric disorders", "hlt": "Mood disorders", "synonyms": ["manic episode", "excessive energy and mood"]},
    {"pt_name": "Bipolar disorder", "pt_code": "10004942", "soc": "Psychiatric disorders", "hlt": "Mood disorders", "synonyms": ["manic depression", "bipolar disorder"]},
    {"pt_name": "Obsessive compulsive disorder", "pt_code": "10031135", "soc": "Psychiatric disorders", "hlt": "Anxiety disorders", "synonyms": ["OCD", "obsessive thoughts and compulsions"]},

    # INFECTIONS (30 terms)
    {"pt_name": "Infection", "pt_code": "10021863", "soc": "Infections", "hlt": "Infections", "synonyms": ["infection", "infected"]},
    {"pt_name": "Sepsis", "pt_code": "10040047", "soc": "Infections", "hlt": "Systemic infections", "synonyms": ["blood poisoning", "septicemia"]},
    {"pt_name": "Septic shock", "pt_code": "10040048", "soc": "Infections", "hlt": "Systemic infections", "synonyms": ["severe sepsis", "sepsis with shock"]},
    {"pt_name": "Urinary tract infection", "pt_code": "10046571", "soc": "Infections", "hlt": "Urinary infections", "synonyms": ["UTI", "bladder infection"]},
    {"pt_name": "Cystitis", "pt_code": "10011702", "soc": "Infections", "hlt": "Urinary infections", "synonyms": ["bladder infection", "painful urination"]},
    {"pt_name": "Nasopharyngitis", "pt_code": "10028810", "soc": "Infections", "hlt": "Upper respiratory infections", "synonyms": ["common cold", "cold"]},
    {"pt_name": "Pharyngitis", "pt_code": "10034735", "soc": "Infections", "hlt": "Upper respiratory infections", "synonyms": ["sore throat", "throat infection"]},
    {"pt_name": "Tonsillitis", "pt_code": "10044120", "soc": "Infections", "hlt": "Upper respiratory infections", "synonyms": ["inflamed tonsils", "swollen tonsils"]},
    {"pt_name": "Sinusitis", "pt_code": "10040736", "soc": "Infections", "hlt": "Upper respiratory infections", "synonyms": ["sinus infection", "sinus inflammation"]},
    {"pt_name": "Otitis media", "pt_code": "10031239", "soc": "Infections", "hlt": "Ear infections", "synonyms": ["ear infection", "middle ear infection"]},
    {"pt_name": "Otitis externa", "pt_code": "10031238", "soc": "Infections", "hlt": "Ear infections", "synonyms": ["outer ear infection", "swimmer's ear"]},
    {"pt_name": "Mastoiditis", "pt_code": "10026345", "soc": "Infections", "hlt": "Ear infections", "synonyms": ["mastoid bone infection", "bone behind ear infection"]},
    {"pt_name": "Labyrinthitis", "pt_code": "10023576", "soc": "Infections", "hlt": "Ear infections", "synonyms": ["inner ear infection", "balance system infection"]},
    {"pt_name": "Meningitis", "pt_code": "10027393", "soc": "Infections", "hlt": "Central nervous system infections", "synonyms": ["brain lining infection", "meningeal infection"]},
    {"pt_name": "Encephalitis", "pt_code": "10014761", "soc": "Infections", "hlt": "Central nervous system infections", "synonyms": ["brain inflammation", "inflamed brain"]},
    {"pt_name": "Appendicitis", "pt_code": "10002671", "soc": "Infections", "hlt": "Gastrointestinal infections", "synonyms": ["appendix infection", "inflamed appendix"]},
    {"pt_name": "Abscess", "pt_code": "10000470", "soc": "Infections", "hlt": "Skin infections", "synonyms": ["pus-filled lump", "boil"]},
    {"pt_name": "Cellulitis", "pt_code": "10008299", "soc": "Infections", "hlt": "Skin infections", "synonyms": ["skin infection", "skin inflammation infection"]},
    {"pt_name": "Impetigo", "pt_code": "10021534", "soc": "Infections", "hlt": "Skin infections", "synonyms": ["strep infection of skin", "contagious skin infection"]},
    {"pt_name": "Fungal infection", "pt_code": "10017012", "soc": "Infections", "hlt": "Fungal infections", "synonyms": ["yeast infection", "fungus infection"]},

    # IMMUNE/ALLERGIC (20 terms)
    {"pt_name": "Anaphylaxis", "pt_code": "10002198", "soc": "Immune disorders", "hlt": "Allergic reactions", "synonyms": ["anaphylactic reaction", "severe allergy"]},
    {"pt_name": "Hypersensitivity", "pt_code": "10020751", "soc": "Immune disorders", "hlt": "Allergic reactions", "synonyms": ["allergic reaction", "allergy"]},
    {"pt_name": "Angioedema", "pt_code": "10002424", "soc": "Immune disorders", "hlt": "Allergic swelling", "synonyms": ["facial swelling", "throat swelling"]},
    {"pt_name": "Urticaria", "pt_code": "10046735", "soc": "Immune disorders", "hlt": "Allergic reactions", "synonyms": ["hives", "skin welts"]},
    {"pt_name": "Drug rash with eosinophilia and systemic symptoms", "pt_code": "10013786", "soc": "Immune disorders", "hlt": "Allergic reactions", "synonyms": ["DRESS syndrome", "drug hypersensitivity"]},
    {"pt_name": "Serum sickness", "pt_code": "10040082", "soc": "Immune disorders", "hlt": "Allergic reactions", "synonyms": ["serum sickness-like reaction", "immune reaction"]},
    {"pt_name": "Immune system disorder", "pt_code": "10021863", "soc": "Immune disorders", "hlt": "Immune disorders", "synonyms": ["immune system problem", "immune dysfunction"]},
    {"pt_name": "Lymphadenopathy", "pt_code": "10024878", "soc": "Immune disorders", "hlt": "Lymphoid disorders", "synonyms": ["swollen lymph nodes", "enlarged lymph glands"]},
    {"pt_name": "Splenomegaly", "pt_code": "10041798", "soc": "Immune disorders", "hlt": "Lymphoid disorders", "synonyms": ["enlarged spleen", "swollen spleen"]},
    {"pt_name": "Hepatosplenomegaly", "pt_code": "10019715", "soc": "Immune disorders", "hlt": "Lymphoid disorders", "synonyms": ["enlarged liver and spleen", "swollen liver and spleen"]},

    # EYE DISORDERS (20 terms)
    {"pt_name": "Blurred vision", "pt_code": "10005886", "soc": "Eye disorders", "hlt": "Visual disorders", "synonyms": ["unclear vision", "hazy vision"]},
    {"pt_name": "Dry eye", "pt_code": "10013774", "soc": "Eye disorders", "hlt": "Eye surface disorders", "synonyms": ["dry eyes", "gritty eyes"]},
    {"pt_name": "Eye irritation", "pt_code": "10015929", "soc": "Eye disorders", "hlt": "Eye surface disorders", "synonyms": ["irritated eyes", "red eyes"]},
    {"pt_name": "Conjunctivitis", "pt_code": "10010741", "soc": "Eye disorders", "hlt": "Eye surface disorders", "synonyms": ["pink eye", "red eye infection"]},
    {"pt_name": "Glaucoma", "pt_code": "10018304", "soc": "Eye disorders", "hlt": "Optic nerve disorders", "synonyms": ["high eye pressure", "optic nerve damage"]},
    {"pt_name": "Cataract", "pt_code": "10007784", "soc": "Eye disorders", "hlt": "Lens disorders", "synonyms": ["cloudy lens", "lens opacity"]},
    {"pt_name": "Retinal detachment", "pt_code": "10038776", "soc": "Eye disorders", "hlt": "Retinal disorders", "synonyms": ["detached retina", "retina tearing off"]},
    {"pt_name": "Macular degeneration", "pt_code": "10025408", "soc": "Eye disorders", "hlt": "Retinal disorders", "synonyms": ["AMD", "central vision loss"]},
    {"pt_name": "Diplopia", "pt_code": "10013023", "soc": "Eye disorders", "hlt": "Binocular disorders", "synonyms": ["double vision", "seeing double"]},
    {"pt_name": "Photophobia", "pt_code": "10034960", "soc": "Eye disorders", "hlt": "Eye sensory disorders", "synonyms": ["light sensitivity", "eyes hurt in light"]},
    {"pt_name": "Lacrimation increased", "pt_code": "10023644", "soc": "Eye disorders", "hlt": "Eye surface disorders", "synonyms": ["watery eyes", "tearing up"]},
    {"pt_name": "Visual field defect", "pt_code": "10047531", "soc": "Eye disorders", "hlt": "Visual disorders", "synonyms": ["blind spot", "missing part of vision"]},
    {"pt_name": "Optic neuritis", "pt_code": "10031121", "soc": "Eye disorders", "hlt": "Optic nerve disorders", "synonyms": ["optic nerve inflammation", "eye nerve inflammation"]},
    {"pt_name": "Uveitis", "pt_code": "10046851", "soc": "Eye disorders", "hlt": "Uveal disorders", "synonyms": ["eye inflammation", "inside eye inflammation"]},
    {"pt_name": "Iritis", "pt_code": "10022616", "soc": "Eye disorders", "hlt": "Uveal disorders", "synonyms": ["iris inflammation", "colored part of eye inflamed"]},
    {"pt_name": "Keratitis", "pt_code": "10023332", "soc": "Eye disorders", "hlt": "Eye surface disorders", "synonyms": ["cornea inflammation", "corneal infection"]},
    {"pt_name": "Blepharitis", "pt_code": "10005148", "soc": "Eye disorders", "hlt": "Eyelid disorders", "synonyms": ["eyelid inflammation", "crusty eyelids"]},
    {"pt_name": "Ptosis", "pt_code": "10037185", "soc": "Eye disorders", "hlt": "Eyelid disorders", "synonyms": ["drooping eyelid", "eyelid droop"]},
    {"pt_name": "Papilloedema", "pt_code": "10033644", "soc": "Eye disorders", "hlt": "Optic nerve disorders", "synonyms": ["swollen optic disc", "raised eye pressure sign"]},
    {"pt_name": "Scotoma", "pt_code": "10039877", "soc": "Eye disorders", "hlt": "Visual disorders", "synonyms": ["blind spot in vision", "area of decreased vision"]},

    # EAR DISORDERS (15 terms)
    {"pt_name": "Tinnitus", "pt_code": "10043882", "soc": "Ear disorders", "hlt": "Hearing disorders", "synonyms": ["ringing in ears", "buzzing in ears"]},
    {"pt_name": "Hearing loss", "pt_code": "10019245", "soc": "Ear disorders", "hlt": "Hearing disorders", "synonyms": ["deafness", "difficulty hearing"]},
    {"pt_name": "Deafness", "pt_code": "10011878", "soc": "Ear disorders", "hlt": "Hearing disorders", "synonyms": ["complete hearing loss", "can't hear"]},
    {"pt_name": "Hypoacusis", "pt_code": "10020856", "soc": "Ear disorders", "hlt": "Hearing disorders", "synonyms": ["reduced hearing", "partial hearing loss"]},
    {"pt_name": "Vertigo", "pt_code": "10047340", "soc": "Ear disorders", "hlt": "Vestibular disorders", "synonyms": ["room spinning", "dizziness and balance problem"]},
    {"pt_name": "Ear pain", "pt_code": "10014020", "soc": "Ear disorders", "hlt": "Ear symptoms", "synonyms": ["earache", "painful ear"]},
    {"pt_name": "Ear discharge", "pt_code": "10014012", "soc": "Ear disorders", "hlt": "Ear symptoms", "synonyms": ["fluid from ear", "drainage from ear"]},
    {"pt_name": "Eustachian tube disorder", "pt_code": "10015490", "soc": "Ear disorders", "hlt": "Ear tube disorders", "synonyms": ["blocked ear tube", "ear pressure problem"]},
    {"pt_name": "Hyperacusis", "pt_code": "10020679", "soc": "Ear disorders", "hlt": "Hearing disorders", "synonyms": ["sound sensitivity", "sensitive to noise"]},
    {"pt_name": "Otalgia", "pt_code": "10031224", "soc": "Ear disorders", "hlt": "Ear symptoms", "synonyms": ["earache", "ear pain"]},

    # REPRODUCTIVE DISORDERS (20 terms)
    {"pt_name": "Erectile dysfunction", "pt_code": "10061461", "soc": "Reproductive disorders", "hlt": "Male reproductive disorders", "synonyms": ["impotence", "ED"]},
    {"pt_name": "Menstrual disorder", "pt_code": "10027313", "soc": "Reproductive disorders", "hlt": "Menstrual disorders", "synonyms": ["irregular periods", "abnormal periods"]},
    {"pt_name": "Amenorrhoea", "pt_code": "10001928", "soc": "Reproductive disorders", "hlt": "Menstrual disorders", "synonyms": ["missed periods", "no periods"]},
    {"pt_name": "Dysmenorrhoea", "pt_code": "10013935", "soc": "Reproductive disorders", "hlt": "Menstrual disorders", "synonyms": ["painful periods", "menstrual cramps"]},
    {"pt_name": "Menorrhagia", "pt_code": "10027282", "soc": "Reproductive disorders", "hlt": "Menstrual disorders", "synonyms": ["heavy periods", "heavy menstrual bleeding"]},
    {"pt_name": "Vaginal discharge", "pt_code": "10046901", "soc": "Reproductive disorders", "hlt": "Female reproductive disorders", "synonyms": ["abnormal vaginal discharge", "unusual discharge"]},
    {"pt_name": "Vaginal haemorrhage", "pt_code": "10046904", "soc": "Reproductive disorders", "hlt": "Female reproductive disorders", "synonyms": ["vaginal bleeding", "abnormal uterine bleeding"]},
    {"pt_name": "Priapism", "pt_code": "10036597", "soc": "Reproductive disorders", "hlt": "Male reproductive disorders", "synonyms": ["painful prolonged erection", "persistent erection"]},
    {"pt_name": "Decreased libido", "pt_code": "10011912", "soc": "Reproductive disorders", "hlt": "Sexual function disorders", "synonyms": ["low sex drive", "reduced sexual desire"]},
    {"pt_name": "Foetal death", "pt_code": "10055792", "soc": "Reproductive disorders", "hlt": "Pregnancy complications", "synonyms": ["stillbirth", "fetal death"]},
    {"pt_name": "Abortion spontaneous", "pt_code": "10000209", "soc": "Reproductive disorders", "hlt": "Pregnancy complications", "synonyms": ["miscarriage", "pregnancy loss"]},
    {"pt_name": "Premature labour", "pt_code": "10036486", "soc": "Reproductive disorders", "hlt": "Pregnancy complications", "synonyms": ["early labor", "preterm labor"]},
    {"pt_name": "Polycystic ovaries", "pt_code": "10036042", "soc": "Reproductive disorders", "hlt": "Ovarian disorders", "synonyms": ["PCOS", "ovarian cysts"]},
    {"pt_name": "Endometriosis", "pt_code": "10014803", "soc": "Reproductive disorders", "hlt": "Uterine disorders", "synonyms": ["uterine tissue outside uterus", "endometrial tissue spreading"]},

    # INVESTIGATIONS/LABORATORY (25 terms)
    {"pt_name": "Alanine aminotransferase increased", "pt_code": "10001551", "soc": "Investigations", "hlt": "Liver function tests", "synonyms": ["elevated ALT", "high liver enzymes"]},
    {"pt_name": "Aspartate aminotransferase increased", "pt_code": "10003481", "soc": "Investigations", "hlt": "Liver function tests", "synonyms": ["elevated AST", "high liver enzyme"]},
    {"pt_name": "Creatinine increased", "pt_code": "10011368", "soc": "Investigations", "hlt": "Kidney function tests", "synonyms": ["high creatinine", "elevated kidney marker"]},
    {"pt_name": "Blood glucose increased", "pt_code": "10005558", "soc": "Investigations", "hlt": "Metabolic tests", "synonyms": ["high blood sugar", "elevated glucose"]},
    {"pt_name": "Haemoglobin decreased", "pt_code": "10018884", "soc": "Investigations", "hlt": "Haematology tests", "synonyms": ["low haemoglobin", "low Hgb"]},
    {"pt_name": "White blood cell count decreased", "pt_code": "10048300", "soc": "Investigations", "hlt": "Haematology tests", "synonyms": ["low WBC", "low white cells"]},
    {"pt_name": "Platelet count decreased", "pt_code": "10035528", "soc": "Investigations", "hlt": "Haematology tests", "synonyms": ["low platelets", "reduced platelet count"]},
    {"pt_name": "Blood pressure increased", "pt_code": "10005750", "soc": "Investigations", "hlt": "Cardiovascular tests", "synonyms": ["high BP", "elevated blood pressure"]},
    {"pt_name": "Heart rate increased", "pt_code": "10019303", "soc": "Investigations", "hlt": "Cardiovascular tests", "synonyms": ["fast heart rate measurement", "elevated pulse"]},
    {"pt_name": "International normalised ratio increased", "pt_code": "10022595", "soc": "Investigations", "hlt": "Coagulation tests", "synonyms": ["elevated INR", "increased clotting time"]},
    {"pt_name": "Troponin increased", "pt_code": "10058156", "soc": "Investigations", "hlt": "Cardiac biomarkers", "synonyms": ["elevated troponin", "heart enzyme elevated"]},
    {"pt_name": "C-reactive protein increased", "pt_code": "10007785", "soc": "Investigations", "hlt": "Inflammatory markers", "synonyms": ["elevated CRP", "inflammation marker raised"]},
    {"pt_name": "Erythrocyte sedimentation rate increased", "pt_code": "10015151", "soc": "Investigations", "hlt": "Inflammatory markers", "synonyms": ["elevated ESR", "sedimentation rate high"]},
    {"pt_name": "Alkaline phosphatase increased", "pt_code": "10001680", "soc": "Investigations", "hlt": "Liver function tests", "synonyms": ["elevated ALP", "high ALP level"]},
    {"pt_name": "Gamma-glutamyltransferase increased", "pt_code": "10017693", "soc": "Investigations", "hlt": "Liver function tests", "synonyms": ["elevated GGT", "high GGT"]},
    {"pt_name": "Bilirubin increased", "pt_code": "10004787", "soc": "Investigations", "hlt": "Liver function tests", "synonyms": ["high bilirubin", "raised bilirubin"]},
    {"pt_name": "Blood urea increased", "pt_code": "10005842", "soc": "Investigations", "hlt": "Kidney function tests", "synonyms": ["elevated BUN", "high urea"]},
    {"pt_name": "Uric acid increased", "pt_code": "10046519", "soc": "Investigations", "hlt": "Metabolic tests", "synonyms": ["high uric acid", "elevated uric acid"]},
    {"pt_name": "Cholesterol increased", "pt_code": "10008661", "soc": "Investigations", "hlt": "Metabolic tests", "synonyms": ["high cholesterol", "elevated cholesterol"]},
    {"pt_name": "Triglycerides increased", "pt_code": "10044560", "soc": "Investigations", "hlt": "Metabolic tests", "synonyms": ["high triglycerides", "elevated lipids"]},
    {"pt_name": "Thyroid stimulating hormone decreased", "pt_code": "10043893", "soc": "Investigations", "hlt": "Endocrine tests", "synonyms": ["low TSH", "suppressed thyroid hormone"]},
    {"pt_name": "Prostate specific antigen increased", "pt_code": "10036760", "soc": "Investigations", "hlt": "Tumour markers", "synonyms": ["elevated PSA", "high PSA"]},
    {"pt_name": "Oxygen saturation decreased", "pt_code": "10033310", "soc": "Investigations", "hlt": "Respiratory tests", "synonyms": ["low O2 sat", "low oxygen levels"]},

    # INJURY/PROCEDURAL (15 terms)
    {"pt_name": "Fall", "pt_code": "10016173", "soc": "Injury and procedural complications", "hlt": "Falls", "synonyms": ["patient fell", "fell down"]},
    {"pt_name": "Fracture", "pt_code": "10017076", "soc": "Injury and procedural complications", "hlt": "Fractures", "synonyms": ["broken bone", "bone break"]},
    {"pt_name": "Contusion", "pt_code": "10010853", "soc": "Injury and procedural complications", "hlt": "Soft tissue injuries", "synonyms": ["bruise", "bruising"]},
    {"pt_name": "Overdose", "pt_code": "10033307", "soc": "Injury and procedural complications", "hlt": "Toxic effects", "synonyms": ["too much medication", "drug overdose"]},
    {"pt_name": "Medication error", "pt_code": "10027199", "soc": "Injury and procedural complications", "hlt": "Drug errors", "synonyms": ["wrong dose", "dosing error"]},
    {"pt_name": "Drug ineffective", "pt_code": "10013922", "soc": "Injury and procedural complications", "hlt": "Therapeutic effects", "synonyms": ["drug not working", "treatment failure"]},
    {"pt_name": "Wound infection", "pt_code": "10048031", "soc": "Injury and procedural complications", "hlt": "Post-procedural infections", "synonyms": ["infected wound", "wound not healing"]},
    {"pt_name": "Haematoma", "pt_code": "10018987", "soc": "Injury and procedural complications", "hlt": "Vascular injuries", "synonyms": ["blood pooling", "bruise under skin"]},
    {"pt_name": "Seroma", "pt_code": "10040152", "soc": "Injury and procedural complications", "hlt": "Fluid accumulation", "synonyms": ["fluid collection", "pocket of fluid"]},
    {"pt_name": "Laceration", "pt_code": "10023673", "soc": "Injury and procedural complications", "hlt": "Skin injuries", "synonyms": ["cut", "gash"]},
    {"pt_name": "Post procedural pain", "pt_code": "10036184", "soc": "Injury and procedural complications", "hlt": "Post-procedural complications", "synonyms": ["pain after procedure", "post-operative pain"]},
    {"pt_name": "Post procedural haemorrhage", "pt_code": "10036187", "soc": "Injury and procedural complications", "hlt": "Post-procedural complications", "synonyms": ["bleeding after surgery", "post-op bleeding"]},
    {"pt_name": "Post procedural infection", "pt_code": "10059313", "soc": "Injury and procedural complications", "hlt": "Post-procedural infections", "synonyms": ["infection after surgery", "surgical site infection"]},
    {"pt_name": "Anastomotic leak", "pt_code": "10002331", "soc": "Injury and procedural complications", "hlt": "Post-procedural complications", "synonyms": ["bowel join leaking", "surgical join failure"]},
    {"pt_name": "Device failure", "pt_code": "10012263", "soc": "Injury and procedural complications", "hlt": "Medical device events", "synonyms": ["device malfunction", "medical device not working"]},

    # ADDITIONAL GENERAL/MISC (30 terms)
    {"pt_name": "Oedema peripheral", "pt_code": "10030124", "soc": "General disorders", "hlt": "Fluid retention", "synonyms": ["swollen ankles", "leg swelling"]},
    {"pt_name": "Hyperhidrosis", "pt_code": "10020642", "soc": "General disorders", "hlt": "Sweating disorders", "synonyms": ["excessive sweating", "profuse sweating"]},
    {"pt_name": "Night sweats", "pt_code": "10029415", "soc": "General disorders", "hlt": "Sweating disorders", "synonyms": ["sweating at night", "nocturnal sweating"]},
    {"pt_name": "Hot flush", "pt_code": "10020751", "soc": "General disorders", "hlt": "Temperature disorders", "synonyms": ["hot flash", "sudden warmth"]},
    {"pt_name": "Flushing", "pt_code": "10016825", "soc": "General disorders", "hlt": "Skin temperature disorders", "synonyms": ["face redness", "face flushing"]},
    {"pt_name": "Thirst", "pt_code": "10043458", "soc": "General disorders", "hlt": "General symptoms", "synonyms": ["excessive thirst", "always thirsty"]},
    {"pt_name": "Appetite lost", "pt_code": "10002953", "soc": "General disorders", "hlt": "Nutrition disorders", "synonyms": ["loss of appetite", "no appetite"]},
    {"pt_name": "Appetite increased", "pt_code": "10002950", "soc": "General disorders", "hlt": "Nutrition disorders", "synonyms": ["excessive hunger", "always hungry"]},
    {"pt_name": "Pallor", "pt_code": "10033546", "soc": "General disorders", "hlt": "General symptoms", "synonyms": ["paleness", "pale skin"]},
    {"pt_name": "Cyanosis", "pt_code": "10011703", "soc": "General disorders", "hlt": "Circulatory symptoms", "synonyms": ["blue skin", "blue lips"]},
    {"pt_name": "Face oedema", "pt_code": "10016029", "soc": "General disorders", "hlt": "Fluid disorders", "synonyms": ["swollen face", "facial swelling"]},
    {"pt_name": "Generalised oedema", "pt_code": "10018106", "soc": "General disorders", "hlt": "Fluid disorders", "synonyms": ["whole body swelling", "widespread swelling"]},
    {"pt_name": "Non-cardiac chest pain", "pt_code": "10029502", "soc": "General disorders", "hlt": "Chest disorders", "synonyms": ["chest pain not heart-related", "musculoskeletal chest pain"]},
    {"pt_name": "Feeling cold", "pt_code": "10016322", "soc": "General disorders", "hlt": "Temperature disorders", "synonyms": ["always cold", "cold feeling"]},
    {"pt_name": "Body temperature increased", "pt_code": "10005741", "soc": "General disorders", "hlt": "Temperature disorders", "synonyms": ["elevated temperature", "raised body temp"]},
    {"pt_name": "Drug withdrawal syndrome", "pt_code": "10013654", "soc": "General disorders", "hlt": "Drug effects", "synonyms": ["withdrawal symptoms", "stopping drug symptoms"]},
    {"pt_name": "Tolerance decreased", "pt_code": "10044109", "soc": "General disorders", "hlt": "Drug effects", "synonyms": ["drug no longer working", "decreased effect"]},
    {"pt_name": "Therapeutic response decreased", "pt_code": "10043548", "soc": "General disorders", "hlt": "Drug effects", "synonyms": ["treatment less effective", "drug wearing off"]},
    {"pt_name": "Disease progression", "pt_code": "10061818", "soc": "General disorders", "hlt": "Disease course", "synonyms": ["condition getting worse", "worsening disease"]},
    {"pt_name": "Sudden death", "pt_code": "10042434", "soc": "General disorders", "hlt": "General events", "synonyms": ["unexpected death", "sudden cardiac death"]},
    {"pt_name": "Multi-organ failure", "pt_code": "10028373", "soc": "General disorders", "hlt": "General events", "synonyms": ["multiple organ failure", "organs failing"]},
    {"pt_name": "Pain in extremity", "pt_code": "10033425", "soc": "General disorders", "hlt": "Pain", "synonyms": ["limb pain", "arm or leg pain"]},
    {"pt_name": "Abnormal gait", "pt_code": "10000195", "soc": "General disorders", "hlt": "Gait disorders", "synonyms": ["walking abnormally", "trouble walking"]},
    {"pt_name": "Impaired healing", "pt_code": "10021518", "soc": "General disorders", "hlt": "General events", "synonyms": ["wounds not healing", "poor wound healing"]},
    {"pt_name": "Anorexia", "pt_code": "10002566", "soc": "General disorders", "hlt": "Nutrition disorders", "synonyms": ["not eating", "refusing food"]},
    {"pt_name": "Cachexia", "pt_code": "10006906", "soc": "General disorders", "hlt": "Nutrition disorders", "synonyms": ["wasting", "severe weight and muscle loss"]},
    {"pt_name": "Drug tolerance decreased", "pt_code": "10013661", "soc": "General disorders", "hlt": "Drug effects", "synonyms": ["lower tolerance", "less able to handle drug"]},
    {"pt_name": "Condition aggravated", "pt_code": "10010121", "soc": "General disorders", "hlt": "Disease course", "synonyms": ["condition worsened", "symptom got worse"]},
    {"pt_name": "Therapeutic product effect incomplete", "pt_code": "10043543", "soc": "General disorders", "hlt": "Drug effects", "synonyms": ["partial response to treatment", "drug partially working"]},
    {"pt_name": "Feeling abnormal", "pt_code": "10016322", "soc": "General disorders", "hlt": "General symptoms", "synonyms": ["feeling strange", "not feeling right"]},
]


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Building MedDRA knowledge base with {len(MEDDRA_TERMS)} terms...")

    output = []
    for term in MEDDRA_TERMS:
        output.append({
            "pt_name": term["pt_name"],
            "pt_code": term["pt_code"],
            "soc_name": term["soc"],
            "hlt_name": term["hlt"],
            "synonyms": term["synonyms"],
            "search_text": f"{term['pt_name']} | {' | '.join(term['synonyms'])}",
        })

    with open(MEDDRA_TERMS_PATH, "w") as f:
        json.dump(output, f, indent=2)

    soc_counts = {}
    for t in output:
        soc_counts[t["soc_name"]] = soc_counts.get(t["soc_name"], 0) + 1

    print(f"Saved {len(output)} MedDRA terms to {MEDDRA_TERMS_PATH}")
    print("\nBreakdown by SOC:")
    for soc, count in sorted(soc_counts.items(), key=lambda x: -x[1]):
        print(f"  {soc}: {count}")


if __name__ == "__main__":
    main()
